import argparse

def parse_args():
    parser = argparse.ArgumentParser(description='Train Image-based Re-ID',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--TRAIN_DATASET',type=str,default='Market1501')
    parser.add_argument('--VAL_DATASETS',nargs='+',help='train datasets')
    parser.add_argument('--DEVICE_ID',default='0',help='DEVICE_ID')
    parser.add_argument('--LOG_DIR',default='./log',help='LOG_DIR')
    parser.add_argument('--TEST_WEIGHT',default='/home/kiddo/ReidLearngene/person-reid-tiny-baseline-master/pretrained_resnet50/resnet50-19c8e357.pth',help='TEST_WEIGHT')
    parser.add_argument('--SAMPLER',default='triplet',help='SAMPLER')
    parser.add_argument('--PRETRAIN_CHOICE',default=None,help='PRETRAIN_CHOICE')
    parser.add_argument('--PRETRAIN_PATH',default='',help='PRETRAIN_PATH')
    parser.add_argument('--LOSS_TYPE',default='triplet+softmax+center',help='LOSS_TYPE')
    parser.add_argument('--OUTPUT_DIR',default='./output',help='OUTPUT_DIR')
    parser.add_argument('--MAX_EPOCHS',type=int,default=30)
    parser.add_argument('--CHECKPOINT_PERIOD',type=int,default=5)
    parser.add_argument('--EVAL_PERIOD',type=int,default=5)
    parser.add_argument('--LOG_PERIOD',type=int,default=5)
    parser.add_argument('--BATCH_SIZE',type=int,default=256)
    parser.add_argument('--NUM_IMG_PER_ID',type=int,default=4)
    parser.add_argument('--INPUT_SIZE', nargs='+', type=int, default=[256,128])
    parser.add_argument('--training_student_model',type=bool,default=False)
    parser.add_argument('--DATALOADER_NUM_WORKERS',type=int,default=8)
    parser.add_argument('--prefetch_factor',type=int,default=4)
    parser.add_argument('--in_planes',type=int,default=64)
    parser.add_argument('--multipliers', nargs='+', type=int, default=[2,4,8])
    parser.add_argument('--STEPS', nargs='+', type=int, default=[40, 70, 130])
    parser.add_argument('--use_softTrip',type=bool,default=False)
    parser.add_argument('--WARMUP_EPOCHS',type=int,default=10)
    parser.add_argument('--refining_weight_chain',type=bool,default=False)
    parser.add_argument('--BASE_LR',type=float,default=0.00035)
    parser.add_argument('--OPTIMIZER', type=str, default='Adam')
    parser.add_argument('--weight_chain_in_planes',type=int,default=None)
    parser.add_argument('--few_shot_seed',type=int,default=None)
    parser.add_argument('--few_shot_ratio',type=float,default=0.5)

    # parser.add_argument()
    args = parser.parse_args()

    return args
